### ISSUE TITLE
Im getting empty response from specific hosts

### ISSUE THREAD

**Issue by leostereo** [tonydm/smokeping-OpenSSHMikrotikRouterOSPing#1]
Let me show:
After running smokeping --debug comand I can see:
`OpenSSHMikrotikRouterOSPing: 172.22.255.250: got 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00
OpenSSHMikrotikRouterOSPing: 194.41.0.4: got
`
as you can see first host is ok but second is not.
I already tryed running manually the:
` ping 198.41.0.4 count=20 size=56 src-address=190.94.186.XX`
from router and from server
` /usr/bin/ssh -S /tmp/.libnet-openssh-perl/1eaf789b53c5273c7d488469dded4e80 -l smokeping -p 22000 172.17.50.1 -- ping 198.41.0.4 count=20 size=56 src-address=190.94.186.XX`

Both works ok , but smokeping plug in can not get usable output.
Dont know what else to check.

**Comment by tonydm** [comment]
Hi leostero,

I would check the raw result of the query from the router, @output.  Uncomment the debug code on line 132.  Run smokeping and check the log for the raw output.  If there's a result, then the next place to look would the be @times value.  It's a result of parsing @output for just the time data.  If the @output data is not blank but is for some reason oddly formatted and does not pass the regex filter on each line of @output, @times would be invalid and also result in a blank got.

```
if ( $psource ) {
  @output = $ssh->capture("ping $dest count=$pings size=$bytes src-address=$psource");
} else {
  @output = $ssh->capture("ping $dest count=$pings size=$bytes");
}

if ($ssh->error) {
  $self->do_log( "OpenSSHMikrotikRouterOSPing running commands on $source: ".$ssh->error );
  return ();
};

# Debug
# $self->do_log(Dumper \@output);```

**Comment by tonydm** [comment]
It also occurred to me to consider a more obvious reason.  It's happened to me, that I over looked a miss config in the target config.  Please also ensure the Target source, (Optional: psource) and host are correct.  I've fat fingered things that technically still made a valid config but would fail to ping on the router.  Then tested from router it worked.  Then found my config error.  Just making sure we've not overlooked the obvious since it's always the obvious we overlook first.

**Comment by leostereo** [comment]
Dear tony , Today I continue debugin this issue:
I uncommented the line 132 as you mentioned but can not read the output. where should I look for it ? 
What Im doing is running:
` ./smokeping --debug`
from the smokeping binary folder , but output is same here ... and there is nothing at smoke.log file nor meesage.

Target:
Already checked target multiple times just in case and for instance, this works:
`++++ ROOT_SERVER_L
menu = ROOT_SERVER_L
title = ROOT_SERVER_L - 199.7.83.42
probe = OpenSSHMikrotikRouterOSPing
ssh_port = 22000
host = 199.7.83.42
source = 172.17.50.1
psource = 90.94.186.18
`
but this one does not:
`++++ ROOT_SERVER_A
menu = ROOT_SERVER_A
title = ROOT_SERVER_A - 198.41.0.4
probe = OpenSSHMikrotikRouterOSPing
ssh_port = 22000
host = 98.41.0.4
source = 172.17.50.1
psource = 90.94.186.18
`
Then I set forks to 20 just to try.
And finally, tryed without specify psource:
Here the output is ok but then I got another error when updating rrd file:
`
Aug 24 10:57:56 UBUNTU-SMOKE-CORE smokeping[13564]: RRDs::update ERROR: /var/lib/smokeping/PROVEDORES/ITX_LIC/ROOT_SERVERS/ROOT_SERVER_A.rrd: found extra data on update argument: 1.7800000000e-01`

Then , installed smokeping on fresh ubuntu server but have same behavuiour.

Any , thanks for listening, I will continue debuggin this.
Leandro

**Comment by tonydm** [comment]
Hi leostereo,

To further assist you...

Smokeping by default does not create a log file, it will only output to stdout/stderr.  You must specify the logfile option on the command line with smokeping.

```
smokeping --debug --logfile=/tmp/smokeping.log
```
Alternatively, you can log any output you wish to a user specified file by adding this code to your probe file.  This will allow you to separate out just the information you're interested in vs all of the smokeping logging data.  In this case insert it at line 130 in the OpenSSHMikrotikRouterOSPing.pm file.  Be sure to uncomment line #24 so that the Data::Dumper module is loaded.  If you still don't see any data from the @output variable in your logfile, then the problem isn't the probe or Smokeping, but with the OpenSSH library and/or the router and/or target host itself.  If you do see data from the @output variable, add the custom log code snippet below the @times loop to determine the result of @times which is returned to smokeping to then process and update the rrd file.

```
my $filename = "/tmp/mydebugfile.log";
open(FH, '>', $filename) or warn $!;
print FH "Result of \@output...\n";
print FH Dumper \@output;
close(FH);
```

Best
